Upgrade orders api to Java 21
companieshouse/orders.api.ch.gov.uk pull request #154
Opened 2024-03-25 13:42 UTC by vshastri-ch

2024-03-25 14:26 UTC, hwatkins-ch requested changes
Looks good, just a few dependencies that still need upgrading :)

2024-03-25 14:26 UTC, hwatkins-ch commented on pom.xml
>          <commons.lang.version>2.6</commons.lang.version>
This is an old version as the dependency has been moved, can we move to commons-lang3 and get on the latest version of that?

https://mvnrepository.com/artifact/commons-lang/commons-lang

2024-03-25 14:26 UTC, hwatkins-ch commented on pom.xml
>          <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
Can we upgrade maptruct version to the latest, 1.5.5.FINAL?

https://mvnrepository.com/artifact/org.mapstruct/mapstruct

2024-03-25 14:26 UTC, hwatkins-ch commented on pom.xml
>          <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
Can we upgrade this maven-surefire-plugin to 3.2.5? 

https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin

2024-03-25 14:26 UTC, hwatkins-ch commented on pom.xml
>          <jib-maven-plugin.version>3.1.1</jib-maven-plugin.version>
Can we upgrade jib-maven-plugin to 3.4.1?

https://mvnrepository.com/artifact/com.google.cloud.tools/jib-maven-plugin

2024-03-25 14:26 UTC, hwatkins-ch commented on pom.xml
> +            <version>3.2.3</version>
Can we move this to the properties above?

Can we also make sure its the latest version, I believe its up to 4.12.2
https://mvnrepository.com/artifact/de.flapdoodle.embed/de.flapdoodle.embed.mongo

2024-03-25 14:26 UTC, hwatkins-ch commented on pom.xml
> +                <version>3.2.0</version>
Is there any reason we added the version here and removed it from the properties above?

This version can also be upgraded to 3.2.4
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-maven-plugin

2024-03-25 15:09 UTC, vshastri-ch commented on pom.xml
> +                <version>3.2.0</version>
made it 3.2.3 and used the property

2024-03-25 15:25 UTC, foman-ch reviewed
just some unused imports to look at

2024-03-25 15:25 UTC, foman-ch commented on src/main/java/uk/gov/companieshouse/orders/api/controller/OrderController.java
>  import java.time.LocalDateTime;
Is there an unused import here

2024-03-25 15:25 UTC, foman-ch commented on src/main/java/uk/gov/companieshouse/orders/api/interceptor/RequestMapper.java
> +import org.springframework.web.util.ServletRequestPathUtils;
Looks like a couple of these imports aren't used

2024-03-26 14:54 UTC, hwatkins-ch approved these changes

2024-03-26 14:54 UTC, hwatkins-ch commented
Just a quick one, is it worth squashing your commits? I see there are a lot of merge commits, which I don't think we want going into our main branch.

2024-03-26 14:58 UTC, vshastri-ch commented
Will squash commits for sure. thanks!

2024-03-27 11:31 UTC, foman-ch approved these changes
Changes look good to me!

2024-03-27 13:42 UTC, merged